version: '3.9'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
      - ./bkp:/bkp
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_DB=teste
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_INITDB_ARGS=--auth-host=trust
    ports:
      - 5435:5432
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    container_name: vrpostgresfiscal